// A connection package's declared status, read without validating the rest of its contract: what
// the release manifest and the default custom-gatekeeper selection use to hold an unreviewed
// connector back. Kept apart from `connection-package.ts` so those readers need no schema validator.

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

/** The file a connection package's contract lives in, at the package root. */
export const CONNECTION_FILE = "connection.json";

/**
 * How far a connection package has come, in order. Only a person moves a package along it:
 *
 * - `scaffold`: generated by `pnpm gatekeepers:scaffold`, not reviewed. It may run locally.
 * - `conformant`: its agent-facing contract was reviewed and it passes the shared conformance suite
 *   against its fake provider. It may run locally; it is still not shipped.
 * - `reference`: additionally reviewed as the pattern others copy, against a real provider contract.
 * - `production`: additionally accepted live.
 *
 * Scaffolding alone never produces anything past `scaffold`.
 */
export const CONNECTION_STATUSES = ["scaffold", "conformant", "reference", "production"] as const;

/** One step of {@link CONNECTION_STATUSES}. */
export type ConnectionStatus = typeof CONNECTION_STATUSES[number];

/** Statuses a release ships and the default custom-gatekeeper selection binds. */
export const RELEASED_STATUSES: ReadonlySet<ConnectionStatus> = new Set(["reference", "production"]);

/**
 * The status a package directory declares, read without schema validation: what the release
 * manifest and the default selection use to hold an unreviewed connector back. `null` when the
 * package has no `connection.json` (it is not a connection package) or names no known status, which
 * the callers treat as unreviewed whenever the file exists.
 */
export function declaredStatus(dir: string): ConnectionStatus | null {
  const path = join(dir, CONNECTION_FILE);
  if (!existsSync(path)) return null;
  try {
    const status = (JSON.parse(readFileSync(path, "utf8")) as { status?: unknown }).status;
    return CONNECTION_STATUSES.includes(status as ConnectionStatus) ? status as ConnectionStatus : null;
  } catch {
    return null;
  }
}

/**
 * Whether a package directory is held back from releases and from the default custom-gatekeeper
 * selection: it has a `connection.json` whose status is not one of {@link RELEASED_STATUSES}
 * (including an unreadable or unknown one). A package with no contract is unaffected.
 */
export function isUnreleasedConnection(dir: string): boolean {
  if (!existsSync(join(dir, CONNECTION_FILE))) return false;
  const status = declaredStatus(dir);
  return status === null || !RELEASED_STATUSES.has(status);
}
